language: node_js
node_js:
  - "7"
sudo: required
services:
  - docker
before_install: 
  - npm install -g grunt-cli bower
  - npm install
  - "echo '{ \"allow_root\": true }' > /root/.bowerrc"
  - bower install --quiet --silent
  - mkdir -p build
  - grunt buildProd --out=build > /dev/null
script: docker build -t $DOCKER_REPO:latest;
after_success:
  - if [ ($TRAVIS_BRANCH = 'develop') && ($TRAVIS_PULL_REQUEST == 'false')];
    docker tag -f $DOCKER_REPO:latest;
    docker push $DOCKER_REPO:latest;
  fi;
